<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class bedrijfseeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('bedrijf')->insert([
            [
                'naam'              => 'Elektricien Bakker & Zonen',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Erkende elektriciens voor installaties, storingen en keuringen bij particulier en zakelijk.',
                'beschrijving_lang' => 'Bakker & Zonen is een erkend elektrotechnisch installatiebedrijf met meer dan 30 jaar ervaring. Wij verzorgen complete elektra-installaties voor nieuwbouw en renovatie, lossen storingen snel op en voeren periodieke keuringen uit. Onze monteurs zijn NEN-gecertificeerd en werken altijd veilig en conform de geldende normen. Van een extra stopcontact tot een volledig slimhuis — bij ons bent u aan het juiste adres.',
                'straat'            => 'Industrieweg',
                'huisnummer'        => '34',
                'postcode'          => '2631 RV',
                'plaats'            => 'Nootdorp',
                'telefoon'          => '015 234 56 78',
                'gsm'               => '06 23 45 67 89',
                'email'             => 'info@bakkerelektro.nl',
                'website'           => 'www.bakkerelektro.nl',
                'facebook'          => 'https://facebook.com/bakkerelektro',
                'linkedin'          => null,
                'instagram'         => null,
                'clicks'            => 61,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Dakdekkersbedrijf Vermeulen',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Specialisten in platte en hellende daken, dakisolatie en goterreinigingen.',
                'beschrijving_lang' => 'Dakdekkersbedrijf Vermeulen heeft ruim 20 jaar ervaring in het leggen, repareren en renoveren van alle soorten daken. Of het nu gaat om dakpannen, bitumen, zink of EPDM — wij werken nauwkeurig en met de beste materialen. Ook voor dakinspectie, dakisolatie en gootonderhoud kunt u bij ons terecht. Wij werken door heel Zuid-Holland en omgeving.',
                'straat'            => 'Rijnstraat',
                'huisnummer'        => '12',
                'postcode'          => '2801 BJ',
                'plaats'            => 'Gouda',
                'telefoon'          => '0182 55 66 77',
                'gsm'               => '06 34 56 78 90',
                'email'             => 'info@dakdekkersvermeulen.nl',
                'website'           => 'www.dakdekkersvermeulen.nl',
                'facebook'          => 'https://facebook.com/dakdekkersvermeulen',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/dakdekkersvermeulen',
                'clicks'            => 47,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Timmerwerk & Interieurs Janssen',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Maatwerk in hout: keukens, vloeren, deuren en op maat gemaakte meubels.',
                'beschrijving_lang' => 'Janssen Timmerwerk & Interieurs maakt al jarenlang uw woonwensen waar. Wij vervaardigen op maat gemaakte keukens, kasten, vloeren en interieuronderdelen in hout. Van eenvoudige reparaties tot complete interieurrenovaties — wij denken met u mee en leveren kwaliteit die een leven lang meegaat. Kom langs in onze showroom of vraag een gratis adviesgesprek aan.',
                'straat'            => 'Ambachtsstraat',
                'huisnummer'        => '7',
                'postcode'          => '5612 AL',
                'plaats'            => 'Eindhoven',
                'telefoon'          => '040 765 43 21',
                'gsm'               => '06 45 67 89 01',
                'email'             => 'info@janssenmeubelmakers.nl',
                'website'           => 'www.janssenmeubelmakers.nl',
                'facebook'          => null,
                'linkedin'          => 'https://linkedin.com/company/janssenmeubelmakers',
                'instagram'         => 'https://instagram.com/janssen_interieurs',
                'clicks'            => 35,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Glazenwasserij Peters',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Professioneel ramen wassen voor woningen, kantoren en winkelruimtes.',
                'beschrijving_lang' => 'Glazenwasserij Peters verzorgt al meer dan 10 jaar schone ramen voor particulieren en bedrijven in de regio Utrecht. Wij werken met moderne apparatuur en milieuvriendelijke middelen voor een vlekkeloos resultaat. Of u nu een eenmalige beurt wilt of een vaste onderhoudsabonnement — wij plannen het voor u in. Betrouwbaar, punctueel en betaalbaar.',
                'straat'            => 'Maliebaan',
                'huisnummer'        => '56',
                'postcode'          => '3581 CK',
                'plaats'            => 'Utrecht',
                'telefoon'          => '030 123 78 90',
                'gsm'               => '06 56 78 90 12',
                'email'             => 'info@glazenwasserijpeters.nl',
                'website'           => null,
                'facebook'          => 'https://facebook.com/glazenwasserijpeters',
                'linkedin'          => null,
                'instagram'         => null,
                'clicks'            => 19,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Tuinontwerp & Aanleg De Groenhoek',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Van tuinontwerp tot complete aanleg en onderhoud van uw tuin.',
                'beschrijving_lang' => 'De Groenhoek is uw specialist voor tuinontwerp, -aanleg en -onderhoud in de regio Arnhem en omstreken. Wij ontwerpen tuinen op maat, van kleine stadstuin tot grote landschappelijke aanleg. Onze ervaren tuinarchitecten denken mee over duurzaamheid, waterberging en sfeer. Naast aanleg bieden wij ook seizoensonderhoud, bestratingswerkzaamheden en vijverspecialisten.',
                'straat'            => 'Parkweg',
                'huisnummer'        => '3',
                'postcode'          => '6824 BN',
                'plaats'            => 'Arnhem',
                'telefoon'          => '026 445 67 89',
                'gsm'               => '06 67 89 01 23',
                'email'             => 'info@degroenhoek.nl',
                'website'           => 'www.degroenhoek.nl',
                'facebook'          => 'https://facebook.com/degroenhoek',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/degroenhoek_tuinen',
                'clicks'            => 53,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Autorijschool Rijstijl',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Persoonlijke rijlessen voor uw rijbewijs B, met hoge slagingspercentages.',
                'beschrijving_lang' => 'Bij Autorijschool Rijstijl leert u rijden op een ontspannen en effectieve manier. Onze gediplomeerde instructeurs passen het lestempo aan op uw niveau en ervaring. Wij hebben moderne voertuigen met dubbele bediening en bieden ook spoedcursussen aan. Met een slagingspercentage ruim boven het landelijk gemiddelde bent u bij ons in goede handen. Vraag vrijblijvend een proefles aan!',
                'straat'            => 'Stationsplein',
                'huisnummer'        => '22',
                'postcode'          => '4811 BB',
                'plaats'            => 'Breda',
                'telefoon'          => '076 521 34 56',
                'gsm'               => '06 78 90 12 34',
                'email'             => 'info@autorijschoolrijstijl.nl',
                'website'           => 'www.autorijschoolrijstijl.nl',
                'facebook'          => 'https://facebook.com/rijschoolrijstijl',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/rijstijl_rijschool',
                'clicks'            => 38,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Kapsalon Haargevoel',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Knipjes, kleuren en stylen voor dames, heren en kinderen in een sfeervolle salon.',
                'beschrijving_lang' => 'Kapsalon Haargevoel is het adres voor een knipbeurt met aandacht. Onze ervaren kapsters en kappers luisteren naar uw wensen en geven eerlijk advies over het model dat het beste bij u past. Wij werken met A-merk producten en hechten waarde aan een ontspannen sfeer. Van een simpele knipbeurt tot een complete kleurbehandeling of bruidskapsel — u bent van harte welkom.',
                'straat'            => 'Lange Viestraat',
                'huisnummer'        => '14',
                'postcode'          => '3511 BK',
                'plaats'            => 'Utrecht',
                'telefoon'          => '030 987 12 34',
                'gsm'               => null,
                'email'             => 'info@kapsalonhaargevoel.nl',
                'website'           => 'www.kapsalonhaargevoel.nl',
                'facebook'          => 'https://facebook.com/kapsalonhaargevoel',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/kapsalon_haargevoel',
                'clicks'            => 72,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Bouwbedrijf Hendriksen',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Aannemer voor verbouwingen, uitbouwen, renovaties en nieuwbouwprojecten.',
                'beschrijving_lang' => 'Bouwbedrijf Hendriksen neemt uw bouwproject van A tot Z uit handen. Van het eerste ontwerp en vergunningaanvraag tot de sleuteloplevering — onze uitvoerders en vaklieden zorgen voor een kwalitatief resultaat binnen het afgesproken budget en tijdpad. Wij zijn gespecialiseerd in woning-uitbouwen, dakkapellen, badkamer- en keukenrenovaties en complete verbouwingen. Al meer dan 18 jaar betrouwbaar in de regio.',
                'straat'            => 'Bouwmeesterstraat',
                'huisnummer'        => '9',
                'postcode'          => '1703 DP',
                'plaats'            => 'Heerhugowaard',
                'telefoon'          => '072 567 89 01',
                'gsm'               => '06 89 01 23 45',
                'email'             => 'info@bouwbedrijfhendriksen.nl',
                'website'           => 'www.bouwbedrijfhendriksen.nl',
                'facebook'          => 'https://facebook.com/bouwbedrijfhendriksen',
                'linkedin'          => 'https://linkedin.com/company/hendriksen-bouw',
                'instagram'         => null,
                'clicks'            => 44,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Schoonmaakbedrijf Blinkend Schoon',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Dagelijkse en periodieke schoonmaak voor kantoren, winkels en woningen.',
                'beschrijving_lang' => 'Blinkend Schoon levert professionele schoonmaakdiensten voor particulieren en bedrijven in de regio Den Haag. Wij verzorgen dagelijks of wekelijks onderhoud van kantoren, showrooms en winkels, maar ook eenmalige grote schoonmaken van woningen. Ons team werkt discreet, betrouwbaar en met milieuvriendelijke reinigingsmiddelen. Vraag vandaag nog een offerte aan.',
                'straat'            => 'Laan van NOI',
                'huisnummer'        => '45',
                'postcode'          => '2593 BH',
                'plaats'            => 'Den Haag',
                'telefoon'          => '070 345 67 89',
                'gsm'               => '06 90 12 34 56',
                'email'             => 'info@blinkendschoon.nl',
                'website'           => 'www.blinkendschoon.nl',
                'facebook'          => null,
                'linkedin'          => 'https://linkedin.com/company/blinkendschoon',
                'instagram'         => null,
                'clicks'            => 29,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Fysiotherapie Van Loon',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Fysiotherapeuten voor sport-, rug- en revalidatieklachten, ook aan huis.',
                'beschrijving_lang' => 'Fysiotherapie Van Loon biedt professionele fysiotherapeutische zorg voor iedereen met bewegingsklachten. Onze therapeuten zijn gespecialiseerd in rugpijn, sportblessures, revalidatie na operaties en chronische pijn. Wij werken met moderne behandeltechnieken zoals dry needling, manuele therapie en bekkenfysiotherapie. Behandeling bij ons in de praktijk of aan huis is mogelijk. Rechtstreeks aanmelden zonder verwijzing van de huisarts.',
                'straat'            => 'Koninginneweg',
                'huisnummer'        => '31',
                'postcode'          => '2012 GS',
                'plaats'            => 'Haarlem',
                'telefoon'          => '023 456 78 90',
                'gsm'               => null,
                'email'             => 'info@fysiotherapievanloon.nl',
                'website'           => 'www.fysiotherapievanloon.nl',
                'facebook'          => 'https://facebook.com/fysiotherapievanloon',
                'linkedin'          => null,
                'instagram'         => null,
                'clicks'            => 56,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Accountantskantoor Meijer & Partners',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Administratie, belastingaangiften en financieel advies voor ondernemers.',
                'beschrijving_lang' => 'Meijer & Partners is een modern accountantskantoor dat mkb-ondernemers ontzorgt op het gebied van administratie, belastingen en financieel advies. Wij verzorgen jaarrekeningen, btw-aangiften, salarisadministratie en bedrijfseconomisch advies. Onze adviseurs denken proactief mee en helpen u om financieel gezond te ondernemen. Maak een afspraak voor een gratis kennismakingsgesprek.',
                'straat'            => 'Coolsingel',
                'huisnummer'        => '104',
                'postcode'          => '3011 AG',
                'plaats'            => 'Rotterdam',
                'telefoon'          => '010 222 33 44',
                'gsm'               => null,
                'email'             => 'info@meijerenpartners.nl',
                'website'           => 'www.meijerenpartners.nl',
                'facebook'          => null,
                'linkedin'          => 'https://linkedin.com/company/meijerenpartners',
                'instagram'         => null,
                'clicks'            => 33,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Verhuisbedrijf Snel & Zeker',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Professionele verhuizers voor particuliere en zakelijke verhuizingen door heel Nederland.',
                'beschrijving_lang' => 'Verhuisbedrijf Snel & Zeker neemt de stress van uw verhuizing weg. Ons ervaren team van verhuizers zorgt voor een vlotte en zorgvuldige verhuizing, of u nu naar de buren verhuist of naar de andere kant van Nederland. Wij bieden volledige ontzorging: van inpakken en sjouwen tot het ophangen van lampen in uw nieuwe woning. Vraag eenvoudig online een verhuisofferte aan.',
                'straat'            => 'Transportweg',
                'huisnummer'        => '18',
                'postcode'          => '1332 AM',
                'plaats'            => 'Almere',
                'telefoon'          => '036 678 90 12',
                'gsm'               => '06 12 98 76 54',
                'email'             => 'info@snelenzekerverhuizers.nl',
                'website'           => 'www.snelenzekerverhuizers.nl',
                'facebook'          => 'https://facebook.com/snelenzekerverhuizers',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/snelenzekerverhuizers',
                'clicks'            => 41,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Loodgietersbedrijf Van der Berg',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Vakkundige loodgieters voor al uw sanitair, verwarmings- en rioleringswerkzaamheden.',
                'beschrijving_lang' => 'Loodgietersbedrijf Van der Berg is al meer dan 25 jaar het vertrouwde adres in de regio voor al uw sanitair- en verwarmingswerkzaamheden. Wij leveren service op maat voor zowel particulieren als bedrijven. Of het nu gaat om een lekkende kraan, een nieuwe badkamer of een complete cv-installatie — onze gediplomeerde monteurs staan altijd voor u klaar. Spoedgevallen? Wij zijn 24 uur per dag, 7 dagen per week bereikbaar.',
                'straat'            => 'Keizersgracht',
                'huisnummer'        => '142',
                'postcode'          => '1015 CX',
                'plaats'            => 'Amsterdam',
                'telefoon'          => '020 123 45 67',
                'gsm'               => '06 12 34 56 78',
                'email'             => 'info@vanderberg-loodgieter.nl',
                'website'           => 'www.vanderberg-loodgieter.nl',
                'facebook'          => 'https://facebook.com/vanderbergloodgieter',
                'linkedin'          => 'https://linkedin.com/company/vanderberg',
                'instagram'         => 'https://instagram.com/vanderberg_loodgieter',
                'clicks'            => 42,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'naam'              => 'Schildersbedrijf De Wit',
                'afbeelding'        => null,
                'beschrijving_kort' => 'Professioneel schilderwerk binnen en buiten, voor particulier en zakelijk.',
                'beschrijving_lang' => 'Schildersbedrijf De Wit staat al ruim 15 jaar bekend om zijn vakmanschap en betrouwbaarheid. Wij verzorgen alle soorten schilderwerk: van het schilderen van uw woonkamer tot complete gevelverfraaiing van bedrijfspanden. Wij werken met hoogwaardige materialen en hechten grote waarde aan een nette afwerking en een opgeruimde werkplek. Vraag vrijblijvend een offerte aan — wij komen graag bij u langs voor een persoonlijk advies.',
                'straat'            => 'Dorpsstraat',
                'huisnummer'        => '88',
                'postcode'          => '3271 AK',
                'plaats'            => 'Rotterdam',
                'telefoon'          => '010 987 65 43',
                'gsm'               => '06 98 76 54 32',
                'email'             => 'info@schildersbedrijfdewit.nl',
                'website'           => 'www.schildersbedrijfdewit.nl',
                'facebook'          => 'https://facebook.com/schildersbedrijfdewit',
                'linkedin'          => null,
                'instagram'         => 'https://instagram.com/schildersbedrijf_dewit',
                'clicks'            => 28,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ]);
    }
}
